name: try fetch
on:
  push:
    branches:
      - main
  

jobs:
  data_fetch:
    runs-on: ubuntu-latest
    env:
          INSTANCE_URL: ${{ secrets.INSTANCE_URL }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          MYVAR: MYVAR1
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: "Say Hello Mona it's Monday"
        run: echo "$Greeting $MYVAR. Today is $MYVAR!"


      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run script
        run: |
          pip install requests
          python snowscript.py

      - name: Archive logs
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: app.log
