name: run main.py

 
on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to run ansible-playbook against
        default: DEVINT
        type: choice
        options:
          - DEVINT
          - QAF1
          - QAF2
          - QAF3
          - QAPERF
          - PROD
        required: true
      limit:
        description: Limit hosts ran by passing in a group. Multiple groups by be separated by a comma.
        type: string
        default: ""
        required: false
      secret_id:
        description: The ID of the secret containing the user credentials.
        default: secret-ghar-np
        type: choice
        options:
          - secret-ghar-np
          - svc-prod-ue1-secret-ghar-prod
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      limit:
        type: string
        default: ""
        required: false
      secret_id:
        type: string
        default: "secret-ghar-np"
        required: true
    secrets:
      PASSWORD:
        required: true


jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install requests autopep8

      - name: execute py script # run main.py
        env:
          PASSWORD: ${{ secrets.PASSWORD }}
        run: python snowscript.py
 

