name: test
on:
  push:
    branches:
      - main

jobs:
  data_fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Echo the value of a variable in the workflow
        run: echo "The value of myvar is $myvar"
